spring:
  ## DB相关
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: lixu198511
    tomcat:
      max-active: 20
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis-plus:
  mapper-locations: classpath:xml/*Mapper.xml
  type-aliases-package: com.weixiao.wxpersistent.entity
  global-config:
  # 利用数据库自增
    id-type: 0
    refresh-mapper: true
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
logging:
  level:
    com.weixiao.wxpersistent.mapper: debug


